# Generated by Django 5.0.3 on 2025-03-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(choices=[(0, 'Debug'), (1, 'Info'), (2, 'Warning'), (3, 'Error')], default=1)),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
                ('country', models.CharField(default='', max_length=256)),
                ('ref', models.CharField(default='', max_length=256)),
                ('sid', models.CharField(default='', max_length=256)),
                ('url', models.CharField(default='', max_length=256)),
                ('val1', models.CharField(default='', max_length=256)),
                ('val2', models.CharField(default='', max_length=256)),
                ('val3', models.CharField(default='', max_length=256)),
                ('ip', models.CharField(default='', max_length=256)),
                ('body', models.TextField(default='{}')),
                ('user_agent', models.CharField(default='', max_length=1024)),
                ('device', models.CharField(default='', max_length=256)),
                ('browser', models.CharField(default='', max_length=256)),
                ('browser_family', models.CharField(default='', max_length=256)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_touch_capable', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('os', models.CharField(default='', max_length=256)),
                ('os_family', models.CharField(default='', max_length=256)),
                ('os_version', models.CharField(default='', max_length=256)),
                ('device_family', models.CharField(default='', max_length=256)),
                ('device_brand', models.CharField(default='', max_length=256)),
                ('device_model', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
