# Generated by Django 5.1 on 2024-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(default="INFO", max_length=256)),
                ("name", models.CharField(max_length=256)),
                ("email", models.CharField(default="", max_length=256)),
                ("country", models.CharField(default="", max_length=256)),
                ("ip", models.CharField(default="", max_length=256)),
                ("body", models.TextField(default="{}")),
                ("ref", models.CharField(default="", max_length=256)),
            ],
        ),
    ]
