# Generated by Django 5.0.3 on 2025-03-12 15:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default=app.models.uuid, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('locked_to', models.DateTimeField(blank=True, default=None, null=True)),
                ('locked_by', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
